server:
  port: 8081

spring:
  application:
    name: jd-goods #微服务的名字，用于注册到ncaos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #ncaos控制台的ip地址和端口号
        username: nacos #ncaos登录的账号
        password: nacos #ncaos登录的密码
        group: DEFULT_GROUP