mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1/ecard
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver